### PR TITLE
Refector api-1

### PR DESCRIPTION
**Pull request by wj461**
修了kawaii api裡Reviewing中除了login以外的api
建議Done也確認一遍

### CODE REVIEW

**Comment by huhuhu0420** [comment]
image
/store/{storeID}/shipping-discount
should response object in document, but response array actually

**Comment by wj461** [comment]
> image /store/{storeID}/shipping-discount should response object in document, but response array actually

fix

**Comment by huhuhu0420** [comment]
/store/{storeID}/shipping-discount
如果那家店shipping-discount的狀態都為0，add new discount or get shipping discount 會報500

**Comment by wj461** [comment]
> /store/{storeID}/shipping-discount 如果那家店shipping-discount的狀態都為0，add new discount or get shipping discount 會報500

fix now will return null

**Review by nonorze-VOXX — APPROVED** [review]
IWOMM

**Pull request merged**
