### PR TITLE
Customer cart checkout/get total price/get orders/delet product from cart

### LINKED ISSUE #60: 結帳購物車內的商品

### PR DESCRIPTION
**Pull request by wj461**

### CODE REVIEW

**Review by nonorze-VOXX — CHANGES_REQUESTED** [review]
request get total have some product

**Comment by huhuhu0420** [comment]
i think get-orders should return this:
OrderInfo:
      required:
      - cart_id
      - customer_id
      - seasoning_discount_id
      - shipping_discount_id
      - order_date
      - order_status
      - store_id
      - taking_address
      - taking_method
      - total_price
      - cart_array
      type: object
      properties:
        customer_id:
          type: integer
          format: int64
          example: 1
        seasoning_discount_id:
          type: integer
          format: int64
          example: 1
        shipping_discount_id:
          type: integer
          format: int64
          example: 1
        cart_id:
          type: integer
          format: int64
          example: 1
        store_id:
          type: integer
          format: int64
          example: 1
        order_status:
          type: integer
          format: int64
          example: 1
        order_date:
          type: string
          example: 2021-01-01 00:00:00
        taking_address:
          type: string
          example: NTUT
        taking_method:
          type: integer
          format: int64
          example: 1
        total_price:
          type: integer
          format: int64
          example: 9999
        cart_array:
          type : array
          items:
            $ref: '#/components/schemas/CartInfo'

**Comment by wj461** [comment]
- [api]/customer/{userID}/cart/{cartID}/store/{storeID}/get-total-price
    - [api]/customer/{userID}/orders
    - [api]/customer/{userID}/cart/{cartID}/store/{storeID}/checkout
    - [api]/customer/{userID}/cart/{cartID}/delete/product/{productID}

**Review by nonorze-VOXX — DISMISSED** [review]
ICR

**Comment by wj461** [comment]
> i think get-orders should return this: OrderInfo: required: - cart_id - customer_id - seasoning_discount_id - shipping_discount_id - order_date - order_status - store_id - taking_address - taking_method - total_price - cart_array type: object properties: customer_id: type: integer format: int64 example: 1 seasoning_discount_id: type: integer format: int64 example: 1 shipping_discount_id: type: integer format: int64 example: 1 cart_id: type: integer format: int64 example: 1 store_id: type: integer format: int64 example: 1 order_status: type: integer format: int64 example: 1 order_date: type: string example: 2021-01-01 00:00:00 taking_address: type: string example: NTUT taking_method: type: integer format: int64 example: 1 total_price: type: integer format: int64 example: 9999 cart_array: type : array items: $ref: '#/components/schemas/CartInfo'

fix

**Review by huhuhu0420 — APPROVED** [review]

**Pull request merged**
