### PR TITLE
[sql] sql update

### PR DESCRIPTION
**Pull request by huhuhu0420**
1. format sql
2. insert more data
3. add two more tables: product_label, label_item

### CODE REVIEW

**Comment by nonorze-VOXX** [comment]
```sh
gh pr checkout 75
docker-compose down
docker-compose up
```
```
postgres_db-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/c52-label.sql
postgres_db-1  | 2023-12-04 12:36:47.084 UTC [79] ERROR:  relation "categorys" does not exist
postgres_db-1  | 2023-12-04 12:36:47.084 UTC [79] STATEMENT:  CREATE TABLE
postgres_db-1  |            IF NOT EXISTS labels (
postgres_db-1  |                category_id SERIAL REFERENCES categorys(category_id),
postgres_db-1  |                store_id SERIAL REFERENCES stores(store_id),
postgres_db-1  |                PRIMARY KEY (category_id, store_id)
postgres_db-1  |            );
postgres_db-1  | psql:/docker-entrypoint-initdb.d/c52-label.sql:6: ERROR:  relation "categorys" does not exist
```

**Comment by huhuhu0420** [comment]
fix

**Review by wj461 — APPROVED** [review]
run work

**Review by nonorze-VOXX — APPROVED** [review]
iWOMM

**Pull request merged**
