### PR TITLE
Cart page without function

### LINKED ISSUE #63: 購物車頁面

### PR DESCRIPTION
**Pull request by nonorze-VOXX**

### CODE REVIEW

**Comment by wj461** [comment]
image
where is this

**Comment by wj461** [comment]
image
image
why you don't use the same discount

**Comment by nonorze-VOXX** [comment]
> image where is this

WIP

**Comment by nonorze-VOXX** [comment]
> image image why you don't use the same discount

request svg file of +

**Comment by wj461** [comment]
add label

**Review by huhuhu0420 — APPROVED** [review]

**Pull request merged**
